name: build

on:
  - push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Java setup
        uses: actions/setup-java@v2
        with:
          distribution: "zulu"
          java-version: 8
          cache: "gradle"
      - name: Set outputs
        id: vars
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
      - name: Build With Gradle
        run: bash ./gradlew build
      - name: Rename build artifacts
        run: mv build/libs/Oxygen-*.jar build/libs/Oxygen-${{ steps.vars.outputs.sha_short }}.jar
      - name: Upload build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Oxygen-1.8.9
          path: build/libs/Oxygen-${{ steps.vars.outputs.sha_short }}.jar
